DEBUG=0

GRAVITY=9.81

RANGE=4000  # milimeters

CAM_MOUNT_ORIENTATION = (0, -90, 0) # Camera rotation in the FRD frame - facing down
CAM_MOUNT_POSITION_FRD = (0.085, 0, 0.065) # In meters

FRAME_SCALE = 0.73
FRAME_DIV = 3
FPS = 30 / FRAME_DIV
FRAME_SIZE = (round(240 * FRAME_SCALE), round(180 * FRAME_SCALE))
FRAME_AMPLITUDE_BRIGHTNESS = 0.2
FRAME_DEPTH_BLUR_WIDTH = 5
FRAME_AMPLITUDE_BLUR_WIDTH = 3
FRAME_AMPLITUDE_CLAHE_GRID_SIZE = 8
FRAME_AMPLITUDE_CLAHE_CLIP_LIMIT = 3.0

ICPO_CONFIDENCE=20
ICPO_INIT_RT_DAMPING=0.93

ICPO_MIN_DEPTH=0.1  # meters
ICPO_MAX_DEPTH=4.2  # meters
ICPO_MAX_DEPTH_DIFF=0.2  # meters
ICPO_MAX_POINTS_PART=0.15 # percentage
ICPO_ITER_COUNTS=[1, 10, 10, 10] # Iterations at full res 1/2 res, 1/4 res etc.
ICPO_GRADIENT_MAGNITUDES=[10, 5, 5, 4] # 1, 1/2, 1/4 etc.
